# Generated by Django 5.2.5 on 2025-09-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentASDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droits_validation', models.BooleanField(default=False)),
                ('fonction', models.CharField(blank=True, max_length=100)),
                ('departement', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('demandeur', 'Demandeur'), ('admin', 'Administrateur'), ('agent', 'Agent ASDM')], default='demandeur', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dossierdemande',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='suividossier',
            name='dossier',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='statut',
            new_name='lu',
        ),
        migrations.AddField(
            model_name='notification',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('alert', 'Alerte'), ('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement')], max_length=20),
        ),
        migrations.CreateModel(
            name='DemandeSubvention',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('formation', 'Formation'), ('equipement', 'Equipement'), ('soutien', 'Soutien financier')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_etude', "En cours d'étude"), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True)),
                ('agent_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='app_principale.agentasdm')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_subvention', to='app_principale.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('excel', 'Excel'), ('word', 'Word'), ('autre', 'Autre')], max_length=20)),
                ('chemin_fichier', models.FileField(upload_to='documents/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('taille_fichier', models.BigIntegerField()),
                ('demande_subvention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app_principale.demandesubvention')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('echec', 'Échec'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('demande_subvention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='app_principale.demandesubvention')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=100)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('statistiques', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel')], default='pdf', max_length=20)),
                ('contenu', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='app_principale.agentasdm')),
            ],
        ),
        migrations.AddField(
            model_name='agentasdm',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='app_principale.utilisateur'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app_principale.utilisateur'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='DossierDemande',
        ),
        migrations.DeleteModel(
            name='SuiviDossier',
        ),
    ]
