# Generated by Django 5.2.5 on 2025-09-29 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principale', '0002_agentasdm_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandesubvention',
            name='agent_traitant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='app_principale.utilisateur'),
        ),
    ]
